project_id = "guswjpdwfcrvjqzjswnv"

[functions.batch-prices]
verify_jwt = false

[functions.market-chat]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.oanda-execute]
verify_jwt = false

[functions.forex-auto-trade]
verify_jwt = false

[functions.oanda-pricing]
verify_jwt = false

[functions.site-lock]
verify_jwt = false

[functions.forex-trade-monitor]
verify_jwt = false

[functions.compute-snapshot]
verify_jwt = false

[functions.forex-indicators]
verify_jwt = false
